#自定义视图路由配置，httpmethod（get|delete|post|put|patch）,responetype(html|json|file|xml)
portal:                                      #门户入口
  - httpmethod: 'get'             
    routepath: '/portal'
    description: '首页'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'portal.html' 
about:
  - httpmethod: 'get'
    routepath: '/view/yzj/about'
    description: '关于玄讯'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'about.html'     
industry:
  - httpmethod: 'get'
    routepath: '/view/yzj/industry'
    description: '选择行业'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'industry.html'     
role:
  - httpmethod: 'get'
    routepath: '/view/yzj/role'
    description: '选择角色'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'role.html' 
salesman-work:
  - httpmethod: 'get'
    routepath: '/view/yzj/salesman/work/featurelist'
    description: '功能列表'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'salesman/work/featurelist.html'            
  - httpmethod: 'get'
    routepath: '/view/yzj/salesman/work/check'
    description: '考勤'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'salesman/work/check.html'   
  - httpmethod: 'get'
    routepath: '/view/yzj/salesman/work/terminal'
    description: '附近终端'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'salesman/work/terminal.html'  
  - httpmethod: 'get'
    routepath: '/view/yzj/salesman/work/addterminal'
    description: '增加终端'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'salesman/work/addterminal.html'
  - httpmethod: 'get'
    routepath: '/view/yzj/salesman/work/myterminal'
    description: '我的终端'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'salesman/work/myterminal.html'
  - httpmethod: 'get'
    routepath: '/view/yzj/salesman/work/editterminal'
    description: '修改终端'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'salesman/work/editterminal.html'    
salesman-performance: 
  - httpmethod: 'get'
    routepath: '/view/yzj/salesman/performance/performlist'
    description: '业绩功能列表'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'salesman/performance/performlist.html' 
  - httpmethod: 'get'
    routepath: '/view/yzj/salesman/performance/salesvolumn'
    description: '销量'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'salesman/performance/salesvolumn.html'
  - httpmethod: 'get'
    routepath: '/view/yzj/salesman/performance/rank'
    description: '月度排名'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'salesman/performance/rank.html'      
  - httpmethod: 'get'
    routepath: '/view/yzj/salesman/performance/visit'
    description: '今日拜访'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'salesman/performance/visit.html'
  - httpmethod: 'get'
    routepath: '/view/yzj/salesman/performance/visitstep'
    description: '店面工作(拜访八步骤)'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'salesman/performance/visitstep.html'      
  - httpmethod: 'get'
    routepath: '/view/yzj/salesman/performance/mypromotion'
    description: '促销活动'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'salesman/performance/mypromotion.html'
  - httpmethod: 'get'
    routepath: '/view/yzj/salesman/performance/terminalactivity'
    description: '终端活跃度'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'salesman/performance/terminalactivity.html'
  - httpmethod: 'get'
    routepath: '/view/yzj/salesman/performance/visitreview'
    description: '拜访回顾'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'salesman/performance/visitreview.html'   
  - httpmethod: 'get'
    routepath: '/view/yzj/salesman/performance/relateterminal'
    description: '关联终端'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'salesman/performance/relateterminal.html' 
  - httpmethod: 'get'
    routepath: '/view/yzj/salesman/performance/activedetail'
    description: '终端活跃度明细'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'salesman/performance/activedetail.html'          
charger-work: 
  - httpmethod: 'get'
    routepath: '/view/yzj/charger/work/worklist'
    description: '主管工作列表'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'charger/work/worklist.html' 
  - httpmethod: 'get'
    routepath: '/view/yzj/charger/work/coop_invest'
    description: '协查'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'charger/work/coop_invest.html'  
  - httpmethod: 'get'
    routepath: '/view/yzj/charger/work/agent_check'
    description: '协查'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'charger/work/agent_check.html'      
  - httpmethod: 'get'
    routepath: '/view/yzj/charger/work/check_detail'
    description: '协查'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'charger/work/check_detail.html'    
charger-performance: 
  - httpmethod: 'get'
    routepath: '/view/yzj/charger/performance/chargerlist'
    description: '主管业绩列表'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'charger/performance/chargerlist.html' 
  - httpmethod: 'get'
    routepath: '/view/yzj/charger/performance/salesasync'
    description: '销量分析'
    enableroute: true
    responetype: 'html'
    authorized: true
    physical_file: 'charger/performance/salesasync.html'          