#自定义API路由配置，httpmethod（get|delete|post|put|patch）,responetype(json|file|xml|html)   
about:  
  - httpmethod: 'post'                
    routepath: '/datasource'
    authorized: true
    description: '记录客户信息'
    enableroute: true
    responetype: 'json'
    physical_file: ''
